import { expect, test } from '@playwright/test'

const API = process.env.MAIL_TEST_API_URL ?? 'http://127.0.0.1:18285'

test('mail reception shows outcomes, grouped notices, history and a guarded attachment retry', async ({ page, request }, testInfo) => {
  const state = await (await request.get(`${API}/_mail-test/state`)).json()
  const reception = `/processes/${state.process_id}/reception`
  await page.goto(`/processes/${state.process_id}/settings`)
  const email = page.getByLabel('Correo de recepción (gathering)')
  await expect(email).toHaveValue('')
  await email.selectOption('migration-test@j-aautomation.com')
  await page.getByRole('button', { name: 'Guardar correo', exact: true }).click()
  await expect(email).toHaveValue('migration-test@j-aautomation.com')
  await expect(page.getByText('Pendiente de inicializar', { exact: true })).toBeVisible()
  const start = await request.post(`${API}/_mail-test/start`)
  expect(start.ok(), await start.text()).toBeTruthy()
  await page.goto(reception)
  await expect(page.getByRole('heading', { name: 'Recepción', exact: true })).toBeVisible()
  await expect.poll(async () => (await (await request.get(`${API}/processes/${state.process_id}/mail-ingestion/activity`, { headers: { 'X-User-Id': String(state.user_id) } })).json()).initialized).toBe(true)
  expect((await request.post(`${API}/_mail-test/deliver`)).ok()).toBeTruthy()
  const message = page.getByRole('article').filter({ hasText: 'Synthetic automatic invoice batch' })
  await expect(message).toBeVisible()
  await expect(message.getByRole('link', { name: 'Abrir documento' })).toHaveCount(3)
  await expect(message.getByText('Requiere revisión', { exact: true })).toHaveCount(2)
  await expect(message.getByText('No se pudo procesar', { exact: true })).toHaveCount(0)
  await expect(message.getByRole('link', { name: 'Revisar decisión' })).toHaveCount(1)
  for (const result of ['PAGAR', 'NO PAGAR', 'ESCALAR']) {
    await expect(message.getByText(result, { exact: true })).toBeVisible()
  }
  const toast = page.getByRole('status').filter({ hasText: 'Correo procesado' })
  await expect(toast).toHaveCount(1)
  await expect(toast).toContainText('1 PDF requieren revisión')
  await page.reload()
  await expect(message).toBeVisible()
  await expect(toast).toHaveCount(0)
  await message.getByRole('button', { name: 'Ver historial de intentos' }).click()
  await expect(message.getByText('Lectura iniciada', { exact: true })).toHaveCount(3)
  await expect(message.getByText('Procesamiento terminado', { exact: true })).toBeVisible()
  await page.getByRole('heading', { name: 'Recepción', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('mail-reception.png'), fullPage: true })

  expect((await request.post(`${API}/_mail-test/deliver-retry`)).ok()).toBeTruthy()
  const retry = page.getByRole('article').filter({ hasText: 'Retry one attachment' })
  await expect(retry.getByText('No se pudo procesar', { exact: true })).toBeVisible()
  await expect(retry.getByText('No se ha podido abrir este PDF.', { exact: false })).toBeVisible()
  await retry.getByRole('button', { name: 'Reintentar lectura', exact: true }).click()
  await expect(retry.getByRole('group', { name: 'Confirmar reintento' })).toBeVisible()
  await retry.getByRole('button', { name: 'Confirmar reintento', exact: true }).click()
  await expect(retry.getByRole('link', { name: 'Abrir documento' })).toHaveCount(1)
  await expect(retry.getByRole('button', { name: 'Reintentar lectura', exact: true })).toHaveCount(0)
  await retry.getByRole('button', { name: 'Ver historial de intentos' }).click()
  await expect(retry.getByText('Reintento solicitado', { exact: true })).toBeVisible()
  await expect(retry.getByText('Incidencia registrada:', { exact: false })).toHaveCount(3)

  await page.locator('summary').filter({ hasText: 'Actividad de recepción' }).click()
  await page.getByRole('button', { name: 'Marcar como leído' }).click()
  await expect(page.getByRole('button', { name: 'Marcar como leído' })).toBeDisabled()
  const after = await (await request.get(`${API}/_mail-test/state`)).json()
  expect(after.unchanged).toBe(true)
  expect(after.forbidden).toEqual([])
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('heading', { name: 'Recepción', exact: true }).scrollIntoViewIfNeeded()
  await expect(retry).toBeVisible()
  expect((await retry.boundingBox())?.width).toBeGreaterThan(300)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('mail-reception-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 1280, height: 900 })
  await message.getByRole('link', { name: 'Abrir documento' }).first().click()
  await expect(page.getByText('Recibido por correo · pay.pdf')).toBeVisible()
})
