"""initial schema

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_llm",
        sa.Column("papel", sa.String(), nullable=False),
        sa.Column("modelo", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("papel", name=op.f("pk_config_llm")),
    )
    op.create_table(
        "ficheros",
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("contenido", sa.LargeBinary(), nullable=False),
        sa.Column("texto", sa.String(), nullable=True),
        sa.Column(
            "ingerido", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("hash", name=op.f("pk_ficheros")),
    )
    op.create_table(
        "procesos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=False),
        sa.Column(
            "creado", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_procesos")),
        sa.UniqueConstraint("nombre", name=op.f("uq_procesos_nombre")),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("rol", sa.String(), nullable=False),
        sa.Column(
            "creado", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("rol in ('responsable', 'operador')", name=op.f("ck_usuarios_rol")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("email", name=op.f("uq_usuarios_email")),
    )
    op.create_table(
        "fuentes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proceso_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("origen", sa.String(), nullable=False),
        sa.Column("filas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "cargada", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["proceso_id"], ["procesos.id"], name=op.f("fk_fuentes_proceso_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fuentes")),
    )
    op.create_table(
        "instancias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proceso_id", sa.Integer(), nullable=False),
        sa.Column("fichero_hash", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("estado", sa.String(), nullable=False),
        sa.Column("motivo_revision", sa.String(), nullable=True),
        sa.Column("simbolos", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "estado in ('PENDIENTE', 'REVISION', 'DECIDIDA')", name=op.f("ck_instancias_estado")
        ),
        sa.ForeignKeyConstraint(
            ["fichero_hash"], ["ficheros.hash"], name=op.f("fk_instancias_fichero_hash")
        ),
        sa.ForeignKeyConstraint(
            ["proceso_id"], ["procesos.id"], name=op.f("fk_instancias_proceso_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instancias")),
        sa.UniqueConstraint(
            "proceso_id",
            "nombre",
            "fichero_hash",
            name=op.f("uq_instancias_proceso_id_nombre_fichero_hash"),
        ),
    )
    op.create_table(
        "simbolos",
        sa.Column("proceso_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proceso_id"], ["procesos.id"], name=op.f("fk_simbolos_proceso_id")
        ),
        sa.PrimaryKeyConstraint("proceso_id", "nombre", name=op.f("pk_simbolos")),
    )
    op.create_table(
        "tipos_decision",
        sa.Column("proceso_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("prioridad", sa.Integer(), nullable=False),
        sa.Column("por_defecto", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proceso_id"], ["procesos.id"], name=op.f("fk_tipos_decision_proceso_id")
        ),
        sa.PrimaryKeyConstraint("proceso_id", "nombre", name=op.f("pk_tipos_decision")),
    )
    op.create_table(
        "decisiones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instancia_id", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("resultados", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reglas_hash", sa.String(), nullable=False),
        sa.Column("autor", sa.String(), nullable=False),
        sa.Column("motivo", sa.String(), nullable=True),
        sa.Column(
            "creada", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["instancia_id"], ["instancias.id"], name=op.f("fk_decisiones_instancia_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisiones")),
    )
    op.create_index(
        op.f("ix_decisiones_instancia_id"), "decisiones", ["instancia_id"], unique=False
    )
    op.create_table(
        "eventos",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instancia_id", sa.Integer(), nullable=True),
        sa.Column("paso", sa.String(), nullable=False),
        sa.Column("datos", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("latencia_ms", sa.Integer(), nullable=True),
        sa.Column("coste", sa.Numeric(), nullable=True),
        sa.Column(
            "creado", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["instancia_id"], ["instancias.id"], name=op.f("fk_eventos_instancia_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eventos")),
    )
    op.create_index(op.f("ix_eventos_instancia_id"), "eventos", ["instancia_id"], unique=False)
    op.create_table(
        "extracciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instancia_id", sa.Integer(), nullable=False),
        sa.Column("papel", sa.String(), nullable=False),
        sa.Column("modelo", sa.String(), nullable=False),
        sa.Column("simbolos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("coste", sa.Numeric(), nullable=True),
        sa.Column("latencia_ms", sa.Integer(), nullable=True),
        sa.Column(
            "creada", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["instancia_id"], ["instancias.id"], name=op.f("fk_extracciones_instancia_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extracciones")),
    )
    op.create_table(
        "reglas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proceso_id", sa.Integer(), nullable=False),
        sa.Column("texto", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("codigo_a", sa.String(), nullable=True),
        sa.Column("codigo_b", sa.String(), nullable=True),
        sa.Column("tests_a", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tests_b", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column("estado", sa.String(), nullable=False),
        sa.Column("informe", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "creada", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("activada", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "estado in ('borrador', 'rechazada', 'activa', 'retirada')",
            name=op.f("ck_reglas_estado"),
        ),
        sa.CheckConstraint("tipo in ('requisito', 'prohibicion')", name=op.f("ck_reglas_tipo")),
        sa.ForeignKeyConstraint(
            ["proceso_id", "decision"],
            ["tipos_decision.proceso_id", "tipos_decision.nombre"],
            name=op.f("fk_reglas_proceso_id_decision"),
        ),
        sa.ForeignKeyConstraint(["proceso_id"], ["procesos.id"], name=op.f("fk_reglas_proceso_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reglas")),
    )
    op.create_table(
        "hallazgos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_id", sa.Integer(), nullable=False),
        sa.Column("regla_id", sa.Integer(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("detalle", sa.String(), nullable=True),
        sa.Column(
            "creado", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisiones.id"], name=op.f("fk_hallazgos_decision_id")
        ),
        sa.ForeignKeyConstraint(["regla_id"], ["reglas.id"], name=op.f("fk_hallazgos_regla_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hallazgos")),
    )
    # ### end Alembic commands ###
    config_llm = sa.table("config_llm", sa.column("papel"), sa.column("modelo"))
    op.bulk_insert(
        config_llm,
        [
            {"papel": "compilador_a", "modelo": "anthropic/claude-opus-5"},
            {"papel": "compilador_b", "modelo": "openai/gpt-5"},
            {"papel": "extractor_1", "modelo": "anthropic/claude-sonnet-5"},
            {"papel": "extractor_2", "modelo": "openai/gpt-5-mini"},
            {"papel": "asistente", "modelo": "anthropic/claude-opus-5"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hallazgos")
    op.drop_table("reglas")
    op.drop_table("extracciones")
    op.drop_index(op.f("ix_eventos_instancia_id"), table_name="eventos")
    op.drop_table("eventos")
    op.drop_index(op.f("ix_decisiones_instancia_id"), table_name="decisiones")
    op.drop_table("decisiones")
    op.drop_table("tipos_decision")
    op.drop_table("simbolos")
    op.drop_table("instancias")
    op.drop_table("fuentes")
    op.drop_table("usuarios")
    op.drop_table("procesos")
    op.drop_table("ficheros")
    op.drop_table("config_llm")
    # ### end Alembic commands ###
