"""mail_ingestion

Revision ID: 0018
Revises: 0017
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mail_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("folder", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("uidvalidity", sa.BigInteger(), nullable=True),
        sa.Column("initial_uid", sa.BigInteger(), nullable=True),
        sa.Column("next_uid", sa.BigInteger(), nullable=True),
        sa.Column("last_poll_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["process_id"], ["processes.id"], name=op.f("fk_mail_accounts_process_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_accounts")),
        sa.UniqueConstraint("process_id", name=op.f("uq_mail_accounts_process_id")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_mail_accounts_token_hash")),
    )
    op.create_table(
        "run_operations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("instance_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["process_id"], ["processes.id"], name=op.f("fk_run_operations_process_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_operations")),
        sa.UniqueConstraint("process_id", "key", name=op.f("uq_run_operations_process_id_key")),
    )
    op.create_table(
        "mail_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("uidvalidity", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("metadata_saved", sa.Boolean(), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.String(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["mail_accounts.id"], name=op.f("fk_mail_messages_account_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_messages")),
        sa.UniqueConstraint(
            "account_id",
            "uidvalidity",
            "uid",
            name=op.f("uq_mail_messages_account_id_uidvalidity_uid"),
        ),
    )
    op.create_index(
        op.f("ix_mail_messages_account_id"), "mail_messages", ["account_id"], unique=False
    )
    op.create_table(
        "mail_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("part", sa.String(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("safe_name", sa.String(), nullable=False),
        sa.Column("encoding", sa.String(), nullable=False),
        sa.Column("advertised_size", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("file_hash", sa.String(), nullable=True),
        sa.Column("instance_id", sa.Integer(), nullable=True),
        sa.Column("execution_id", sa.Integer(), nullable=True),
        sa.Column("decision_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisions.id"], name=op.f("fk_mail_attachments_decision_id")
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], name=op.f("fk_mail_attachments_execution_id")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"], ["instances.id"], name=op.f("fk_mail_attachments_instance_id")
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["mail_messages.id"], name=op.f("fk_mail_attachments_message_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_attachments")),
        sa.UniqueConstraint("message_id", "part", name=op.f("uq_mail_attachments_message_id_part")),
    )
    op.create_index(
        op.f("ix_mail_attachments_message_id"), "mail_attachments", ["message_id"], unique=False
    )
    op.add_column("processes", sa.Column("gathering_email", sa.String(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_processes_gathering_email"), "processes", ["gathering_email"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_processes_gathering_email"), "processes", type_="unique")
    op.drop_column("processes", "gathering_email")
    op.drop_index(op.f("ix_mail_attachments_message_id"), table_name="mail_attachments")
    op.drop_table("mail_attachments")
    op.drop_index(op.f("ix_mail_messages_account_id"), table_name="mail_messages")
    op.drop_table("mail_messages")
    op.drop_table("run_operations")
    op.drop_table("mail_accounts")
    # ### end Alembic commands ###
